import { cn } from "@/lib/utils";
import Providers from "@/store/Providers";
import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import NavigationBar from "@/components/header/NavigationBar"

import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Vibanc",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <Providers>
      <html lang="en">
        <body className={cn("", montserrat.className)}>
          <div>

            {/* <NavigationBar /> */}
          </div>

          {children}
          <ToastContainer />
        </body>
      </html>
 
   
    </Providers>
  );
}
